# Generated by Django 3.0.8 on 2020-07-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Target',
        ),
    ]
