# Generated by Django 3.0.8 on 2020-07-29 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0002_auto_20200729_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='obervations_number',
            new_name='observations_number',
        ),
    ]
