# Generated by Django 3.0.8 on 2020-07-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('targets', '0003_auto_20200729_1600'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='target',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='target',
            name='name',
            field=models.CharField(max_length=54, unique=True),
        ),
    ]
